honojs/node-server

src/server.ts
Fixes and edge case with multiple set-cookie headers in a single Response
- multiple `set-cookie` headers in a single `Response` is valid
- comma delimited `set-cookie` values in a single header are invalid (or rather they will not be picked up and set by the browser)
- the res.headers Iterator returns the equivalent of `res.headers.get('set-cookie')` for the value, which is a comma delimited string (and thus invalid)
- this fix will use `res.headers.getAll('set-cookie')` which returns an array of strings which is a valid value in `response.setHeader` https://nodejs.org/docs/latest-v18.x/api/http.html#responsesetheadername-value
=> support multiple set-cookie headers in response

src/server.ts
This change fixes a bug with the handling of `HEAD` requests.
Previously we would never match on a `HEAD` request and thus incorrectly create a body to the request, which would throw an uncaught error
=> fix if statement bug in server

src/server.ts
This change fixes how we write out a response body so that we can support encoded responses
Previously we would cause a content encoding error by calling `res.text()` on responses even if they are encoded (`br`,`gzip` etc). Now we check if the response has the `content-encoding` header and use the read/write stream instead if it does.
=> fix bug with encoded responses

src/globals.ts
With Node.js 19.0, the Web Crypto API is now accessible directly from the global object. global.crypto is not writable so trying to assign to it crashes the program. This is a simple fix for it.
=> global.crypto fix for Node 19.0

README.md, src/serve-static.ts
Added documentation for `path`, which appears to require relative paths.
It was not obvious for someone porting a project with absolute paths from Express - the error messages were confusing:
```
Static file: ./home/mindplay/workspace/try-hono/public/index.css is not found
```
At a glance, it looks like the file exists - but the `.` at the beginning of course makes it relative to the current working directory.
It's not clear to me whether this is intentional, for platform portability perhaps? Most other Node servers would accept an absolute path - and this middleware only works on Node. But you might want relative paths in Hono projects as a convention?
If this is **not** intentional, you should reject this PR!
=> Must use relative paths

src/listener.ts
Using a ReadableStream instead of buffer.concat provides an improvement in several ways:
1. According to web standards, the request.body should either be null or an instanceof ReadableStream, not Buffer (Uint8Array).
2. In a Hono node server, it's important not to consume the incoming message body until it's actually used.
3. Using a ReadableStream is especially beneficial when clients post large bodies, as it allows the Hono app to be built quickly by the node server.
=> feat: use readable stream for the request body

src/listener.ts, src/stream.ts, test/server.test.ts, tsconfig.json
- Stream transfer;
- Potential crashes;
- Unable to cancel stream flow upon user abort request.
- Only Error types are accepted by outgoing.destroy, but the thrown exception may not be an Error. Use es2022 cause to solve.
=> feat: add stream support and fix some bugs

src/globals.ts, src/listener.ts, src/stream.ts
- Rewrite the implementation of `Stream Pipe`, taking inspiration from nodejs' `stream.Readable.fromWeb`, which offers better support for backpressure and highWatermark option.
- Additionally, TransformStream has been added to globals.
=> fix: add TransformStream to global and re-implement stream pipe

README.md
the previous link targeted a category/grouping page which no longer exists, so instead target the top-most document within the category it used to link to
=> Fix broken built-in middleware link

src/listener.ts, src/server.ts
`type` imports were used in some places,  but not all
=> Refactor imports to type imports

src/serve-static.ts
If we use `Readable.toWeb()`, the tests on CI fail intermittently. Since we can't reproduce this issue in a local environment, it's challenging to fix. Hence, for now, we're avoiding the use of `Readable.toWeb()`.
=> fix: avoid `Readable.toWeb()` which causes CI failure

build.ts, package.json, yarn.lock
With this PR, Node Server adapter will support both CommonJS and ESM.
=> feat: support ESM

package.json, src/listener.ts, src/server.ts, src/types.ts, test/server.test.ts, yarn.lock
This PR will allow passing `createServer` from `node:http2`. Additionally `serverOptions` will have more helpful types
=> allow http2

src/listener.ts
Fix #73 https://github.com/honojs/hono/issues/1253
=> fix: don't `destroy` if `pipeline` throws an error

src/listener.ts
For performance improvement:
1. Cache regexp objects (though I think it's not very effective).
2. Avoid using `res.headers.get()`.
The result on Node.js 20:
=> perf: polish `listener.ts`

src/serve-static.ts, src/utils.ts
I think these changes will bring small performance improvements because :
- the `split` function call will stop when we've retrieved the 2 elements we're using. It also prevents people from putting unnecessary elements in the `Range` header, which can affect performance.
- Reduce multiple assignments on `start` and `end` variables
- Call the `ReadableStream.getReader` function only if the `Writable` is not destroyed.
=> perf: small improvements

src/utils.ts
Hi there! It looks like a bug was introduced in v1.2.2 with the addition of `writeFromReadableStream` in [this PR](https://github.com/honojs/node-server/pull/93). I was able to reproduce this on both Node v18 and v20.
With fast responses on a fast connection the problem isn't as noticeable, but if you're serving large responses (particularly if the response returned from a Hono handler is a ReadableStream that's slow to enqueue chunks), then `writable.end()` in `writeFromReadableStream` is never called. This leads to responses in the browser showing as 'Pending' indefinitely.
I've created a reproduction repo [here](https://github.com/ezg27/hono-node-server-repro) that demonstrates the issue - try adding a log inside the `if (done) {...}` statement in the `flow` function in …
=> fix: handle calling writable.end() correctly

src/listener.ts
It would be better to use `number`, even if it may not affect performance.
> Content-Length is read in bytes, not characters. Use [Buffer.byteLength()](https://github.com/nodejs/node/blob/main/doc/api/buffer.md#static-method-bufferbytelengthstring-encoding) to determine the length of the body in bytes. Node.js will check whether Content-Length and the length of the body which has been transmitted are equal or not.
https://github.com/nodejs/node/blob/main/doc/api/http.md#responsewriteheadstatuscode-statusmessage-headers
=> refactor: set content-length as number with `outgoing.writeHead()`

src/response.ts, test/response.test.ts, test/server.test.ts
fixes #104
This is a bit of a detour, but the cause is that when `new Response(options)` was called in a nested manner, the `options` referred to the same object in memory as the parent and child.
So when we did `this.#res.headers.delete('content-type')` at the following location in hono, all `content-type`s of the parent and child were deleted and the `applicatioin/json` information was lost.
https://github.com/honojs/hono/blob/main/src/context.ts#L145
If the actual global.Response is passed to option when making a nested new call, the header is cloned in it process, so this problem is fixed.
=> fix: Nested `new` call problem

src/listener.ts, test/server.test.ts
Fixes #114
Handling of responses returned from applications that are not `Response` instances, returning a proper response.
=> fix: handle response that is not an instance of `Response`

package.json, src/listener.ts, test/server.test.ts, yarn.lock
Fixes #116
In this PR, it avoids using `instanceOf Response` to determine if a response is right. This means that it will not throw an error when returning a ponyfill Response, e.g. `@whatwg-node/fetch`. The error message is now unfriendly, but this is the correct behavior.
=> fix: don't use `instanceOf Response` when handling response

README.md, src/serve-static.ts, test/serve-static.test.ts
Related #118 , https://github.com/honojs/hono/pull/1825
=> feat(serve-static): introduce `onNotFound` option

src/index.ts, src/listener.ts, src/types.ts, test/server.test.ts
Makes the raw `IncomingMessage` and `ServerResponse` instances accessible via `c.env` the [same way](https://github.com/honojs/hono/blob/main/src/adapter/aws-lambda/handler.ts#L158-L162) that [`hono/aws-lambda` does it](https://hono.dev/getting-started/aws-lambda#access-requestcontext).
After implementing it I saw that #90 does the same thing, but I thought I may as well submit it as it is smaller in scope.
```ts
type Bindings = {
incoming: IncomingMessage
outgoing: ServerResponse
}
const app = new Hono<{ Bindings: Bindings}>()
app.get('/', (c) => {
console.log(c.env.incoming.url)
})
```
Related: #80 #90 #122
=> feat: Forward Raw `IncomingMessage` and `ServerResponse` Via `Env`

src/globals.ts, src/request.ts, test/request.test.ts, test/response.test.ts, test/setup.ts
This PR allows the following code to work, making it easy to replace the Request object in hono.
https://github.com/honojs/node-server/compare/main...usualoma:node-server:feat/create-request-from-request?expand=1#diff-e7c9480196e722de595dba06f56ad6601bce3d0e66651e7b77eea71f93be2ac3R55-R85
=> feat(request): Enable to create Request from light weight request.

src/listener.ts
I've made some slight adjustments to enhance readability.
=> refactor: more readable

src/listener.ts, src/types.ts, test/listener.test.ts
Would ya'll be open to this kind of option? 
Open to alternative approaches, but basically what I'm after is a means for the consumer to be able to provide it's own error handler so that it can, for example, pass the error down the middleware chain in a Vite dev server. This allows vite to display the standard pretty error overlay on the client, etc.
See example of how it can be used in https://github.com/honojs/vite-plugins/pull/63 (this PR blocks that PR).
=> feat(listener): support custom error handler

src/listener.ts, src/request.ts, test/listener.test.ts, test/request.test.ts
When we receive a request, we start listening to the close event. When fired, we check if the request was aborted using `incoming.aborted`, if it was, we dispatch an abort event to the existing request abort signal.
Without this, when the client aborts the request, the signal on the request was not being called with the abort event.
Closes: https://github.com/honojs/node-server/issues/107
=> Catch when nodejs request is aborted

src/listener.ts, src/response.ts, test/server.test.ts
Fixes #144
Reuse the following implementation idea to get the body inside the nodejs Response object and use it to return a response if available.
https://github.com/honojs/node-server/blob/a8117ce9e4f6b1a2615dde1d1b4c2428b801cfa2/src/utils.ts#L13-L24
=> feat: use internal body if available for returning the response in its original form as much as possible

src/request.ts, test/request.test.ts
fixes https://github.com/honojs/node-server/issues/147
=> feat: support keepalive property for Request object

src/request.ts, test/server.test.ts
=> fix(request): guess request protocol from incoming object

src/listener.ts, test/listener.test.ts
=> fix: catch ERR_INVALID_URL error in listener

src/index.ts, src/listener.ts, src/request.ts, src/server.ts, test/listener.test.ts, test/request.test.ts
fixes #160, #161
Validate the content of the host header of the request for security purposes.
If the following values are specified in the host header, a "400 Bad Request" is returned.
* Empty string (if no default hostname is specified)
* Including path or query parameter
* `localhost/path` `localhost?key=value`
* Including invalid charactors
* `localhost<script>`
Host headers are only validated by character type, so "hostnames with invalid structure" or "hostnames that cannot be looked up" are considered valid and do not result in a "400 Bad Request". For example, the following host headers are considered valid
* `.` `www...example.com`  `()`
If you also want to accept HTTP 1.0 requests w/o Host header, you can call `serve()` as follows to ensure that the default hostname is used …
=> feat: validate incoming host header

src/request.ts, src/response.ts
Some web frameworks (like Remix) inject polyfills for ReadableStream into the Node Runtime.  This change makes sure that the server will work correctly with those polyfills. Otherwise the `instanceof` check would fail.
=> Update Request to work with ReadableStream polyfills

.github/workflows/ci.yml
Node.js 22 will enter long-term support (LTS) in October, so I think it would be a good idea to start running CI on it now.
I've also added workflow permissions and increased action versions.
=> ci: include tests for node 22 version

package.json, src/listener.ts, test/server.test.ts, tsconfig.json
Fixes #171, https://github.com/honojs/hono/issues/2816
Two issues needed to be corrected in this issue.
[The documentation](https://nodejs.org/api/http.html#requestaborted) says "Deprecated. check request.destroyed instead."
However, incoming was flagged for “autodestroy" and `incoming.destroy()` was always called when the request body was read to the end. In other words, `.abort()` was always called in POST requests. POST requests complete successfully, so there are no major problems, but I think it was not a good behaviour.
https://github.com/nodejs/node/blob/c0c598d753d5ce7e1721215c6e6254dc02c023a8/lib/internal/streams/readable.js#L1690-L1716
As [errored](https://nodejs.org/api/stream.html#readableerrored) seemed more suitable for our application, I decided to use it.
The real problem …
=> fix:  memory leak by AbortController

README.md, src/serve-static.ts
Also update the ts doc string for this parameter to be clearer
***
I noticed [in Discord](https://discord.com/channels/1011308539819597844/1012485912409690122/1247001132648239114) that people have trouble with the `root` parameter when using `serveStatic`. I also ran into this issue myself!
This PR updates the README with an example that should hopefully make its usage clearer.
=> Update readme with an example of proper "root" when using serveStatic

src/request.ts, test/server.test.ts
fixes #167
The Request object defined in undici is an error if we try to create it by specifying the TRACE method. In this pull request, create it by specifying the GET method to avoid this.
=> fix: avoid error when using TRACE method

package.json, test/server.test.ts, yarn.lock
Fixes https://github.com/honojs/hono/issues/2251#issuecomment-2200629833
=> fix: make `hono` as external to build

src/listener.ts, test/server.test.ts
fixes #186
"etag" middleware does `res.clone()`, but if you use `Buffer.from`, the internal data is shared, so that once data is read with ’etag’, it could not be re-read on the server side.
https://github.com/usualoma/hono/blob/915a8234975b8b875edcdf6a3acc8280dfc898af/src/middleware/etag/index.ts#L66
In such cases, if you read from `res.body`, the undici handles it well, so you can fallback to `res.body`.
=> fix: return response from res.body if internal data is not ready to be returned directly

README.md, src/serve-static.ts, test/serve-static.test.ts
Implemented the same feature of https://github.com/honojs/hono/pull/3396.
=> feat(serve-static): add `onFound` option

README.md, src/serve-static.ts, test/assets/static-with-precompressed/hello.txt, test/assets/static-with-precompressed/hello.txt.br, test/assets/static-with-precompressed/hello.txt.zst, test/serve-static.test.ts
Implemented the same feature of https://github.com/honojs/hono/pull/3366
=> feat(serve-static): add `precompressed` option

src/serve-static.ts, test/serve-static.test.ts
This pull request is a port of the following pull request.
https://github.com/honojs/hono/pull/3415
=> fix(serve-static): use application/octet-stream if the mime type is not detected

src/server.ts, test/server.test.ts
For node's server.listen, if no hostname param is specified it'll adaptively pick the unspecified ipv6 address (`::`) when available or the unspecified ipv4 address (`0.0.0.0`) otherwise. This fix gets rid of the behavior where we manually default to `0.0.0.0` and rely on node's underlying handling of this.
Since most modern systems should support ipv6, I also added a test case on this new behavior.
See here for the docs on node: https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback:~:text=If%20host%20is%20omitted%2C%20the%20server%20will%20accept%20connections%20on%20the%20unspecified%20IPv6%20address%20(%3A%3A)%20when%20IPv6%20is%20available%2C%20or%20the%20unspecified%20IPv4%20address%20(0.0.0.0)%20otherwise.
=> fix(serve): support ipv6 by default

src/serve-static.ts, test/serve-static.test.ts
This PR adds an error handler for potentially thrown `URIError` during `decodeURIComponent` that should result in a HTTP 404 rather than an HTTP 500 error. 
This may happen if the encoded uri component contains an [invalid sequence encoding](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent):
> [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError)
Thrown if encodedURI contains a % not followed by two hexadecimal digits, or if the escape sequence does not encode a valid UTF-8 character.
Also added a test for this case 👓
=> fix(serve-static): add error handler for decoding uri components

src/utils.ts
At runtime headers may not be an `instanceof` Headers. 
This causes a lot of bugs. 
the function may get a js object as an argument. 
Instead of looping directly through `headers`, I get the entries then loop through them.
=> fix: TypeError: headers is not iterable

src/utils.ts, test/utils.test.ts
I understand that `res.headers` is not necessarily an instance of `Headers` when combined with another framework. In this kind of environment, I think it is safe to assume that it will return either HeadersInit, null, or undefined.
I think it would be better to keep the code from v1.13.3 as it is for processing the contents of the header, and to call `new Headers()` if it is not `Headers`.  The reason is as follows
* The header name is case-insensitive, so you cannot compare it directly using an Object key, such as `=== 'set-cookie'`
* The value “ should be preserved without being deleted
=> fix(utils): accept HeadersInit, null, undefined in buildOutgoingHttpHeaders

src/listener.ts, test/listener.test.ts
Fix detection client premature close (connection abort).
Ref: honojs/node-server#217
=> fix: detection of client premature close

src/types.ts
Makes the ServerOptions type definition publicly accessible by adding the export keyword, allowing it to be imported and used by other modules that depend on this package.
=> fix: export ServerOptions type

src/request.ts, test/request.test.ts
In some environments (e.g. firebase functions), the body is already consumed, but we can re-read the request body from `incoming.rawBody` in that case.
fix https://github.com/honojs/hono/issues/1695
=> fix: re-read request body from `incoming.rawBody` if available

src/listener.ts, src/request.ts, test/listener.test.ts, test/request.test.ts
Fixes https://github.com/honojs/hono/issues/1695
At this time, since the user is not listening for abort events, so we should return immediately.
=> fix: Avoid error if connection is aborted before internal request object is created

src/serve-static.ts
Fix for https://github.com/honojs/node-server/issues/230
Ran `bun run test -- ./test/serve-static.test.ts` and all tests pass.
=> fix: #230 use node:fs specifier prefix vs. fs import

src/listener.ts, test/listener.test.ts
It looks like during a refactor this logic got changed incorrectly. You need to await the promise in this catch block. Otherwise any error thrown inside `responseViaResponseObject` won't get caught and will bubble out the top.
=> fix: Handle Response Errors Correctly

src/listener.ts, src/response.ts, test/response.test.ts, test/server.test.ts
This PR adopts https://github.com/usualoma/node-server/pull/3, excludes https://github.com/honojs/node-server/pull/241, and completely removes the functionality of `getInternalBody`.
In d72de8d, I made the optimization pattern previously covered by `getInternalBody` return from a faster cache.
```ts
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
const app = new Hono()
app.get('/', () => {
const res = new Response('foo')
res.headers.set('x-foo', 'bar')
return res
})
app.get('/uint8array', () => {
return new Response(new Uint8Array([102, 111, 111])) // prints "foo"
})
app.get('/blob', () => {
return new Response(new Blob([new Uint8Array([102, 111, 111])])) // prints "foo"
})
serve({
fetch: app.fetch,
port: 3003,
})
```
```
$ bombardier -d 10s --fasthttp …
```
=> perf: keep using the lightweight Response object when retrieving `headers`, `status`, and `ok`, and then drop the `getInternalBody` function.

src/listener.ts, test/server.test.ts
fixes: #244
Even if data is not immediately written from a ReadableStream, the header is sent without waiting for the data.
Yes, in the case of Http2ServerResponse, there is no need to explicitly flush because the header is sent without waiting for the data.
No, it is not related. node-server has always behaved this way.
=> feat: flush headers before sending data via readable stream

src/serve-static.ts, test/assets/static-with-context-path/plain.txt, test/serve-static.test.ts
=> feat(serve-static): pass context to `rewriteRequestPath`

README.md
Sorry for the minor change, I wanted to split the paragraphs, but they weren't separated in the first PR.
=> docs: separate description of autoCleanupIncoming

.github/workflows/ci.yml, README.md, package.json, src/serve-static.ts, test/serve-static.test.ts
Fixies #187
Related to #203  #238
This PR enables serve-static to support absolute paths, but both `root` and `path` options.
I considered that we should move the serve-static feature to the main `honojs/hono` core related to #203 https://github.com/honojs/hono/issues/3483. However, if so, we need to update the peer dependencies for `hono` so that we can add this feature to this project separately from `honojs/hono`.
=> feat(serve-static): support absolute path

.github/workflows/ci.yml
We have to add `v24 to the CI.
=> ci: add Node.js `v24` for CI

src/listener.ts, test/server.test.ts
fixes #266
If the application did not include `Transfer-Encoding: chunked`, depending on the timing of enqueue, it would loop indefinitely until the second chunk was read.
One way to do this is to treat `text/event-stream` as special, as @yusukebe pointed out in this comment, but I would prefer to resolve this without depending on a specific `Content-Type`.
https://github.com/honojs/node-server/pull/265#discussion_r2241271562
Essentially, the problem was simply [#265](https://github.com/honojs/node-server/pull/265)'s `i--` and `currentReadPromise = reader.read()`, so I think that fixing that should be sufficient without any additional logical changes.
https://github.com/usualoma/hono-se-266
=> fix(listener): Limit retries to a maximum of three.

src/request.ts, test/request.test.ts
#269
Stop generating heavy `global.Request` just by accessing `req.headers`.
This eliminates the memory consumption that until now was caused by simply applying the simple middleware called `cors()`, which generated a `global.Request` and was hard to free up until `GC` was executed.
In situations where we accept a lot of lightweight POST requests, this pull request will not improve on memory usage.
=> fix: Keep lightweight request even if accessing method, url or headers

src/listener.ts
I got an error because `instanceof` wouldn't recognize `res` as a `Promise`. 
Might be related to my usage of `tsx`, idk if it breaks the prototype chain or something.
Anyway, if I change to check for a `then` method, everything works again.
=> fix: Refactor promise check for response handling

src/utils.ts, test/utils.test.ts
fix: #279
There may be compatibility issues with other frameworks or existing implementations on different servers; however, calling `cancel()` appears to be the correct approach according to web standards.
=> fix: cancel a readable stream if a writable stream is closed before a readable stream is closed.
